// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cknwqdttlrrnqhktntuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrbndxZHR0bHJybnFoa3RudHV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNTY4NjMsImV4cCI6MjA3MzgzMjg2M30.fD3WxkMilRLxCSBUvyGFRrj9FhxNT50STOO9RJd2i78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});